# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: proto/app.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import proto.app_pb2 as proto_dot_app__pb2


class VentionAppService(Protocol):
    async def ping(self, request: proto_dot_app__pb2.PingRequest, ctx: RequestContext) -> proto_dot_app__pb2.PingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def heartbeat(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> AsyncIterator[proto_dot_app__pb2.HeartbeatMessage]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class VentionAppServiceASGIApplication(ConnectASGIApplication):
    def __init__(self, service: VentionAppService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/vention.app.v1.VentionAppService/ping": Endpoint.unary(
                    method=MethodInfo(
                        name="ping",
                        service_name="vention.app.v1.VentionAppService",
                        input=proto_dot_app__pb2.PingRequest,
                        output=proto_dot_app__pb2.PingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.ping,
                ),
                "/vention.app.v1.VentionAppService/heartbeat": Endpoint.server_stream(
                    method=MethodInfo(
                        name="heartbeat",
                        service_name="vention.app.v1.VentionAppService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=proto_dot_app__pb2.HeartbeatMessage,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.heartbeat,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/vention.app.v1.VentionAppService"


class VentionAppServiceClient(ConnectClient):
    async def ping(
        self,
        request: proto_dot_app__pb2.PingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_app__pb2.PingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ping",
                service_name="vention.app.v1.VentionAppService",
                input=proto_dot_app__pb2.PingRequest,
                output=proto_dot_app__pb2.PingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def heartbeat(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[proto_dot_app__pb2.HeartbeatMessage]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="heartbeat",
                service_name="vention.app.v1.VentionAppService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=proto_dot_app__pb2.HeartbeatMessage,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class VentionAppServiceSync(Protocol):
    def ping(self, request: proto_dot_app__pb2.PingRequest, ctx: RequestContext) -> proto_dot_app__pb2.PingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def heartbeat(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> Iterator[proto_dot_app__pb2.HeartbeatMessage]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class VentionAppServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: VentionAppServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/vention.app.v1.VentionAppService/ping": EndpointSync.unary(
                    method=MethodInfo(
                        name="ping",
                        service_name="vention.app.v1.VentionAppService",
                        input=proto_dot_app__pb2.PingRequest,
                        output=proto_dot_app__pb2.PingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.ping,
                ),
                "/vention.app.v1.VentionAppService/heartbeat": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="heartbeat",
                        service_name="vention.app.v1.VentionAppService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=proto_dot_app__pb2.HeartbeatMessage,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.heartbeat,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/vention.app.v1.VentionAppService"


class VentionAppServiceClientSync(ConnectClientSync):
    def ping(
        self,
        request: proto_dot_app__pb2.PingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_app__pb2.PingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ping",
                service_name="vention.app.v1.VentionAppService",
                input=proto_dot_app__pb2.PingRequest,
                output=proto_dot_app__pb2.PingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def heartbeat(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[proto_dot_app__pb2.HeartbeatMessage]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="heartbeat",
                service_name="vention.app.v1.VentionAppService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=proto_dot_app__pb2.HeartbeatMessage,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
