from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

from models import JobRecipe, Components, MachineState
from config import API_PORT, API_HOST, DATABASE_URL
from storage.bootstrap import bootstrap
from storage.accessor import ModelAccessor

# Initialize FastAPI app
app = FastAPI(
    title="Starter Template API",
    description="API for machine control and configuration",
    version="1.0.0"
)

# Add CORS middleware for frontend communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize accessors
job_recipe_accessor = ModelAccessor(JobRecipe, "job_recipe")
components_accessor = ModelAccessor(Components, "components")
machine_state_accessor = ModelAccessor(MachineState, "machine_state")

# Bootstrap storage system
bootstrap(
    app,
    accessors=[job_recipe_accessor, components_accessor, machine_state_accessor],
    database_url=DATABASE_URL,
    create_tables=True,
    enable_db_router=True
)

# Note: Components endpoints are auto-generated by vention-storage
# Available at: GET /components/, POST /components/, PUT /components/{id}, DELETE /components/{id}

# Health check endpoint
@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "service": "machine-code-demo-api"}

if __name__ == "__main__":
    uvicorn.run(app, host=API_HOST, port=API_PORT)
